version: "3.2"
services:
    storagenode:
        image: storjlabs/storagenode:beta
        container_name: storagenode
        ports:
            - 28967:28967
            - 14002:14002
        environment:
            - "WALLET=0x123456789"
            - "EMAIL=your@email.com"
            - "ADDRESS=DDNS:28967"
            - "STORAGE=5TB"     
        volumes:
            - type: bind
              source: /your_volume/identity/storagenode
              target: /app/identity
            - type: bind
              source: /your_volume/storage
              target: /app/config
        restart: unless-stopped
    watchtower:
        image: storjlabs/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
        restart: always
        command:  --interval 21600 --stop-timeout 300s 
    storage_exporter:
        image: anclrii/storj-exporter:latest
        container_name: storage_exporter
        ports:
            - 9652:9651
        restart: unless-stopped
        links:
            - storagenode
